name = "kami-undang"
compatibility_date = "2024-11-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "kami-undang-db"
database_id = "ce8276de-ad0c-4c1d-b9a9-4efe04d982df"
migrations_dir = "server/db/migrations"
