name = "kami-undang"
compatibility_date = "2024-11-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "premium-invitation-db"
database_id = "bb43abd1-bf7c-4119-a685-7150b358f2eb"
migrations_dir = "server/db/migrations"
