name = "premium-invitation"
compatibility_date = "2024-11-11"
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "premium-invitation-db"
database_id = "INSERT_YOUR_D1_DATABASE_ID_HERE"
migrations_dir = "server/db/migrations"
